# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detect_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DREAM_EYE(object):
    def setupUi(self, DREAM_EYE):
        DREAM_EYE.setObjectName("DREAM_EYE")
        DREAM_EYE.resize(936, 636)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../ui_img/icon.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DREAM_EYE.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(DREAM_EYE)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(640, 10, 311, 621))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(11)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 270, 271, 151))
        self.groupBox_2.setObjectName("groupBox_2")
        self.camera = QtWidgets.QRadioButton(self.groupBox_2)
        self.camera.setGeometry(QtCore.QRect(20, 30, 89, 16))
        self.camera.setObjectName("camera")
        self.video = QtWidgets.QRadioButton(self.groupBox_2)
        self.video.setGeometry(QtCore.QRect(140, 30, 89, 16))
        self.video.setObjectName("video")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.label.setObjectName("label")
        self.select_video = QtWidgets.QPushButton(self.groupBox_2)
        self.select_video.setGeometry(QtCore.QRect(30, 110, 81, 31))
        self.select_video.setObjectName("select_video")
        self.start_skim = QtWidgets.QPushButton(self.groupBox_2)
        self.start_skim.setGeometry(QtCore.QRect(150, 110, 81, 31))
        self.start_skim.setObjectName("start_skim")
        self.video_path = QtWidgets.QTextEdit(self.groupBox_2)
        self.video_path.setGeometry(QtCore.QRect(110, 60, 151, 31))
        self.video_path.setObjectName("video_path")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 30, 271, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.eye = QtWidgets.QCheckBox(self.groupBox_3)
        self.eye.setGeometry(QtCore.QRect(20, 30, 91, 21))
        self.eye.setObjectName("eye")
        self.ha = QtWidgets.QCheckBox(self.groupBox_3)
        self.ha.setGeometry(QtCore.QRect(150, 30, 91, 21))
        self.ha.setObjectName("ha")
        self.head = QtWidgets.QCheckBox(self.groupBox_3)
        self.head.setGeometry(QtCore.QRect(20, 70, 91, 21))
        self.head.setObjectName("head")
        self.tired = QtWidgets.QCheckBox(self.groupBox_3)
        self.tired.setGeometry(QtCore.QRect(150, 70, 91, 21))
        self.tired.setObjectName("tired")
        self.groupBox_5 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 430, 271, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.log = QtWidgets.QTextBrowser(self.groupBox_5)
        self.log.setGeometry(QtCore.QRect(10, 30, 251, 141))
        self.log.setObjectName("log")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 150, 271, 111))
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox_4)
        self.label_3.setGeometry(QtCore.QRect(20, 30, 81, 21))
        self.label_3.setObjectName("label_3")
        self.tired_time = QtWidgets.QSpinBox(self.groupBox_4)
        self.tired_time.setGeometry(QtCore.QRect(100, 30, 42, 22))
        self.tired_time.setObjectName("tired_time")
        self.label_4 = QtWidgets.QLabel(self.groupBox_4)
        self.label_4.setGeometry(QtCore.QRect(20, 70, 81, 21))
        self.label_4.setObjectName("label_4")
        self.tired_count = QtWidgets.QSpinBox(self.groupBox_4)
        self.tired_count.setGeometry(QtCore.QRect(100, 70, 42, 22))
        self.tired_count.setObjectName("tired_count")
        self.capture = QtWidgets.QLabel(self.centralwidget)
        self.capture.setGeometry(QtCore.QRect(10, 10, 611, 611))
        self.capture.setText("")
        self.capture.setObjectName("capture")
        DREAM_EYE.setCentralWidget(self.centralwidget)

        self.retranslateUi(DREAM_EYE)
        QtCore.QMetaObject.connectSlotsByName(DREAM_EYE)

    def retranslateUi(self, DREAM_EYE):
        _translate = QtCore.QCoreApplication.translate
        DREAM_EYE.setWindowTitle(_translate("DREAM_EYE", "疲劳检测系统"))
        self.groupBox.setTitle(_translate("DREAM_EYE", "参数设置"))
        self.groupBox_2.setTitle(_translate("DREAM_EYE", "视频源"))
        self.camera.setText(_translate("DREAM_EYE", "摄像头"))
        self.video.setText(_translate("DREAM_EYE", "视频文件"))
        self.label.setText(_translate("DREAM_EYE", "视频地址："))
        self.select_video.setText(_translate("DREAM_EYE", "选择文件"))
        self.start_skim.setText(_translate("DREAM_EYE", "确定"))
        self.groupBox_3.setTitle(_translate("DREAM_EYE", "疲劳检测"))
        self.eye.setText(_translate("DREAM_EYE", "闭眼检测"))
        self.ha.setText(_translate("DREAM_EYE", "哈欠检测"))
        self.head.setText(_translate("DREAM_EYE", "瞌睡检测"))
        self.tired.setText(_translate("DREAM_EYE", "疲劳预警"))
        self.groupBox_5.setTitle(_translate("DREAM_EYE", "输出"))
        self.groupBox_4.setTitle(_translate("DREAM_EYE", "检测设置"))
        self.label_3.setText(_translate("DREAM_EYE", "疲劳时间："))
        self.label_4.setText(_translate("DREAM_EYE", "疲劳次数："))

